[package]

name = "rbot"
version = "0.0.1"
authors = ["Antti Keränen <detegr@gmail.com>"]

[dependencies.rbot_parser]
git = "https://github.com/Detegr/RBot-parser.git"

[dependencies]
unix_socket = "^0.4"
ctrlc = "*"
bufstream = "*"

[features]
default = ["unix_socket/socket_timeout"]
