[package]
authors = ["Antti Keränen <detegr@gmail.com>"]
name = "rbot"
version = "0.0.1"

[dependencies]
bufstream = "*"
ctrlc = "*"
time = "0.1.35"
timer = "0.1.6"
unix_socket = "^0.4"

[features]
default = ["unix_socket/socket_timeout"]
