[package]

name = "rbot"
version = "0.0.1"
authors = ["Antti Keränen <detegr@gmail.com>"]

[dependencies]
nom = "*"
unix_socket = "^0.4"
ctrlc = "*"
bufstream = "*"

[features]
default = ["unix_socket/socket_timeout"]
