[package]

name = "rbot"
version = "0.0.1"
authors = ["Antti Keränen <detegr@gmail.com>"]

[dependencies]
nom = "*"

[dependencies.ctrlc]
git = "https://github.com/Detegr/rust-ctrlc"

[dependencies.unix_socket]
unix_socket = "0.3.2"
